# Generated by Django 6.0.8 on 2026-09-19 10:26

from django.db import migrations, models
from django.utils import timezone


def mark_existing_users_verified(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.filter(email_verified_at__isnull=True).update(
        email_verified_at=timezone.now()
    )


def mark_existing_users_unverified(apps, schema_editor):
    User = apps.get_model("users", "User")
    User.objects.update(email_verified_at=None)


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_password_changed_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_verified_at",
            field=models.DateTimeField(
                blank=True,
                null=True,
                verbose_name="дата подтверждения почты",
            ),
        ),
        migrations.RunPython(
            mark_existing_users_verified,
            mark_existing_users_unverified,
        ),
    ]
