services:
  web:
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.prod
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m,mode=1777
      - /home/app/.gunicorn:rw,noexec,nosuid,size=1m,mode=0700,uid=10001,gid=10001
    cpus: 1.0
    mem_limit: 512m
    pids_limit: 128

  db:
    user: postgres
    cap_drop: [ALL]
    security_opt: [no-new-privileges:true]
    tmpfs:
      - /tmp:rw,noexec,nosuid,size=64m,mode=1777
      - /var/run/postgresql:rw,noexec,nosuid,size=16m,mode=1777
    cpus: 1.0
    mem_limit: 512m
    pids_limit: 128
