# Generated by Django 6.0.8 on 2026-09-18 21:05

import ads.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "На рассмотрении"),
                            ("published", "Опубликовано"),
                            ("archived", "Снято с публикации"),
                        ],
                        default="published",
                        max_length=16,
                        verbose_name="состояние",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("scripts", "Скрипты и код"),
                            ("freelance", "Фриланс"),
                            ("courses", "Курсы и обучение"),
                            ("solutions", "Готовые решения"),
                            ("hardware", "Железо"),
                        ],
                        default="scripts",
                        max_length=16,
                        verbose_name="рубрика",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="название")),
                ("price", models.PositiveIntegerField(verbose_name="цена")),
                ("description", models.TextField(verbose_name="описание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="ads/%Y/%m/",
                        validators=[ads.validators.validate_ad_image],
                        verbose_name="фотография",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                (
                    "submitted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="дата отправки на рассмотрение"),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="ads", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "verbose_name": "объявление",
                "verbose_name_plural": "объявления",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "kind",
                    models.CharField(
                        choices=[("review", "Отзыв"), ("question", "Вопрос")],
                        default="review",
                        max_length=16,
                        verbose_name="вид",
                    ),
                ),
                ("text", models.TextField(verbose_name="текст")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="дата создания")),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reviews", to="ads.ad"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="ads.review",
                        verbose_name="ответ на",
                    ),
                ),
            ],
            options={
                "verbose_name": "отзыв",
                "verbose_name_plural": "отзывы",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
